### General
arrowParens: always
tabWidth: 4
useTabs: false
requirePragma: false
insertPragma: false

### VueJS
vueIndentScriptAndStyle: true

### PHP
phpVersion: "8.0"
trailingCommaPHP: true
braceStyle: psr-2

### Pattern-specific
overrides:
  - files:
      - "*.js"
      - "*.ts"
      - "*.jsx"
      - "*.tsx"
      - "*.vue"
    options:
      singleQuote: true
      semi: false
      trailingComma: none
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      tabWidth: 2
      singleQuote: false
  - files: "*.php"
    options:
      singleQuote: true
      printWidth: 120
